### ISSUE TITLE
how to get standard output of generate_multihetsep.py

### ISSUE THREAD

**Issue by Jacky-Chein** [stschiff/msmc-tools#10]
Dear author,
I am a newphyte to msmc. sorry for the naive question.
I used the following command, which was based on your manual, in order to generate input files for msmc analysis. But it seems that the command dose not show standard output. How to get the files likes "input_msmc.chr1.txt" and "input_msmc.chr2.txt" from the following command ?

python3 generate_multihetsep.py  --mask=laosa20/out_mask.bed.gz --mask=laos_a26/out_mask.bed.gz --mask=../mappability_mask/susScr3_chrchr1.mask.bed.gz  laosa20/out.vcf.gz laos_a26/out.vcf.gz

All the best,
Jianhai

**Comment by stschiff** [comment]
Looks correct to me, not sure what’s going on. Note that the code in generate_multihetsep.py is not too hard to understand, perhaps you can find out yourself?

Stephan
