### ISSUE TITLE
mask behavior

### ISSUE THREAD

**Issue by stsmall** [stschiff/msmc-tools#12]
Hi Stephan,
I need a quick clarification on the mask option when using many samples and many masks. I have a single negative mask for each chromosome which denotes regions that were repeated, I also have a mappability mask for each sample but it is negative. Is this the correct way to apply:
generate_multihetsep.py --negative_mask CHROM1.bed.gz --negative_mask uncalled_sample1.bed.gz --negative_mask uncalled_sample2.bed.gz sample1.vcf.gz sample2.vcf.gz.
Are the mask flags need to be the same order to apply to each individual sample? Do I need a similar file name/string, here sample1 and sample2. to appear in both vcf and beds?
thanks,
scott

**Comment by stschiff** [comment]
Dear Scott.

No, the order and names of masks is irrelevant. The command line looks correct. The masks are all combined to a single positive intersection mask, i.e. regions which are present in all given positive masks and absent from all given negative masks.

Stephan
