### ISSUE TITLE
cgCaller.py problem

### ISSUE THREAD

**Issue by houzhe1991** [stschiff/msmc-tools#13]
Dear All,

I got some error when using the cgCaller.py, here is the log

Traceback (most recent call last):
File "./bamCaller.py", line 28, in 
mask = utils.MaskGenerator(args.mask, chr_)
AttributeError: module 'utils' has no attribute 'MaskGenerator'

Could you help me figure it out?
Thanks a lot,

Best,
Langqing

**Comment by stschiff** [comment]
can't reproduce.
