### ISSUE TITLE
Complete Genomics format

### ISSUE THREAD

**Issue by PattSS** [stschiff/msmc-tools#15]
I am analyzing data generated by complete genomics for which I have the access to the mastervarbeta-file. For some samples, when I am running the cgCaller.py script I got this error:

Traceback (most recent call last):
  File "/msmc-tools/cgCaller.py", line 81, in <module>
    assert end - begin == 1
AssertionError

I think this is because for these samples the format version is 2.4. 
How can I fix this problem?

Thanks.
Patricia

**Comment by stschiff** [comment]
Sorry, I'm not really supporting this format anymore. The python code is very straight forward, please try to fix it if possible.
