### ISSUE TITLE
Can we use multi sample vcf and then split it as per chromosome and individual 

### ISSUE THREAD

**Issue by anubhabkhan** [stschiff/msmc-tools#18]
Hi,

I already have a multi sample vcf. I filtered all the SNPs for genotype quality and base quality 30.
Can I use this as an input for MSMC? I am splitting the vcf to generate several files per chromosome and per individual. Can I use these directly for generate_multihetsep step?

Thanks
Anubhab

**Comment by stschiff** [comment]
I would in that case rather write your own little script that converts the VCF to a multihetsep file. The only issue is the masks. You need to assume something for the regions between the segregating sites. Assuming them all to be called homozygous reference may not be appropriate depending on your coverage. 

Stephan

**Comment by anubhabkhan** [comment]
I mostly have average sequencing depths of 24-30X depth.
Is there a way to create just the mask files so that the process is quick?

With regards and yours sincerely

Anubhab
Research Scholar,
National Centre for Biological Sciences,
Tata Institute of Fundamental Research,
India

**Comment by stschiff** [comment]
Yes, by using my bamCaller script on the bam files. But you could also generate masks using some different rule set, e.g. by saying: I include all sites at which 90% of individuals have a high quality genotype called, or something like that. But you would definitely need to go to the bam level. If you have a multi-sample VCF that only contains segregating sites, you have lost information on non-segregating sites.

Stephan
