### ISSUE TITLE
mappability mask ?

### ISSUE THREAD

**Issue by yuntwang** [stschiff/msmc-tools#19]
Hi,@stschiff 
I saw the document of msmc and a little confused:
in the guide:
./generate_multihetsep.py --mask=covered_sites_sample1_chr1.bed.txt.gz \
                          --mask=covered_sites_sample2_chr1.bed.txt.gz \
                          --mask=mappability_mask_chr1.bed.txt.gz \
                          sample1_chr1.vcf.gz sample2_chr1.vcf.gz
Why only one mappability_mask? 
There should be one for each chromosome per sample,is it right?
In addition, if i delete the ' --mask=mappability_mask_chr1.bed.txt.gz',have a big effect on the result?

**Comment by stschiff** [comment]
No, the mappability mask is a property of the reference genome, so there is only one mask per chromosome, which is used for all samples. I don't think that omitting the mappability mask will have huge effects on the results, but certainly some. And it's the conservative thing to do.
