### ISSUE TITLE
explicitly close files

### ISSUE THREAD

**Issue by mhinsch** [stschiff/msmc-tools#2]
On our cluster bamCaller.py sometimes generates empty or truncated mask files. Explicitly closing the file handle used by MaskGenerator at the end of the script appears to help.

**Comment by stschiff** [comment]
Oh I see... thanks for the hint, I'll look into it and get back to you.

**Comment by stschiff** [comment]
Sorry, this thread's been very old. I haven't done anything about it. If you feel like it, send me a pull request.
