### ISSUE TITLE
Huge 

### ISSUE THREAD

**Issue by hugang123** [stschiff/msmc-tools#20]
Hi, i found it was so slow when i analysised more than 500 samples as the reference genome was more than 10G.So i wanted to know could i filter the SNP with LD to reduce the huge inputfile. Does the way  have a effect on the result? (more than 110M snp, i used msmc2 version) Thanks.

**Comment by stschiff** [comment]
You can't run MSMC on 500 genomes, that is about 2 orders of magnitude too large!!! Try to run it on two genomes first and see what happens. You can't filter by LD, since LD is exactly the information that MSMC relies on.
