### ISSUE TITLE
The m parameter (mutant rate)

### ISSUE THREAD

**Issue by hugang123** [stschiff/msmc-tools#21]
Hi,I was confused with the u parameter when i used the code to plot graph

mu <- 1.25e-8
gen <- 30

 As you said "Note that here we have scaled times and rates using a generation time of 30 years and a mutation rate of 1.25e-8",i don't know whether the mu represent the generation mutant rate or just the per year mutant rate. Usually we just had the evolutionary rate (per base per year).So should i use the evolutionary rate multiply the 20 years as the mu  if the species generation is 20 years? Or else?

Thanks a lot.

**Comment by stschiff** [comment]
Are you referring to the code in plot_utils.py?

As you can see in the code, you always have t * gen / mu in the code as real time in years. That means that here mu is the per-generation mutation rate, and gen is the generation time. Alternatively, you can set gen=1 and give the per-year mutation rate directly. That’s the same.

Stephan
