### ISSUE TITLE
Is the relatedness/inbreeding will affect the MSMC results

### ISSUE THREAD

**Issue by yongzhiyang2012** [stschiff/msmc-tools#22]
Hi, everyone. 
I was using the msmc2 pipeline to estimate the demographic. 
But in my study, the four individuals with a high relatedness at a 1st-degree to 3rd-degree (king software result).  So, I want to know is the relatedness will affect the MSMC analysis? If so, what should I do to get the correct results?

**Comment by stschiff** [comment]
Hi,

such a close relatedness will most certainly affect results. MSMC’s model explicitly assumes a well-mixing Wright-Fisher population, so close relatedness will create extremely low population sizes in the most recent time, I guess.

I don’t know an easy solution, other than scanning the data for long IBD blocks and excluding those from the analysis.

Stephan

**Comment by yongzhiyang2012** [comment]
Thanks. I will delete the high relatedness individuals and reanalysis the rest samples with msmc2.

**Comment by yongzhiyang2012** [comment]
Hi, Stephan.
When running msmc2, 2-haplotypes (one individual), 4-haplotypes (two individuals), and 8-haplotypes (three individuals) are usually used. But, 6-haplotypes (three individuals) are rarely seen. 
Can I use 6-haplotypes to infer the demographic? 6-haplotypes will be more accurate than 4-haplotypes in the most recent population history?

**Comment by stschiff** [comment]
Yes, you can and yes I think it will be more accurate than 4.

Stephan

**Comment by yongzhiyang2012** [comment]
Thank you again for your Immediately reply and I will try the 6-haplotypes.
