### ISSUE TITLE
Workflow guideline and plotting the results

### ISSUE THREAD

**Issue by zillurbmb51** [stschiff/msmc-tools#25]
Hi there,
I was trying to infer population histroy of my single sample organism. My workflow is following:

1.  samtools mpileup -q 20 -Q 20 -C 50 -u -r Pf3D7_02_v3 -f pfal.fa SRR1027715_NoDupRealigned.bam | bcftools call -c -V indels | ../msmc-tools/bamCaller.py 172 chr2_mask.bed.gz | gzip -c > chr2.vcf.gz (for all chromosome)
2. ./../msmc-tools/generate_multihetsep.py --mask=chr14_mask.bed.gz chr14.vcf.gz > chr14.msmc.input.txt (for all chromosomes)
3. /gondor/zillur/tools/msmc2/build/release/msmc2 -o test1.msmc chr1.msmc.input.txt chr2.msmc.input.txt chr3.msmc.input.txt chr4.msmc.input.txt chr5.msmc.input.txt chr6.msmc.input.txt chr7.msmc.input.txt chr8.msmc.input.txt chr9.msmc.input.txt chr10.msmc.input.txt chr11.msmc.input.txt chr12.msmc.input.txt chr13.msmc.input.txt chr14.msmc.input.txt
Which gave me: 1. https://github.com/zillurbmb51/Kajoli/blob/master/test1.msmc.final.txt
and 2. https://github.com/zillurbmb51/Kajoli/blob/master/test1.msmc.loop.txt
Am I on the right path? How can I visualize my results? Is there any example command?

Any help will be greatly appreciated.
Thanks in advance.
Best Regards
Zillur

**Comment by stschiff** [comment]
Please try the tutorial I've written in this repository.
