### ISSUE TITLE
Generate the input file of msmc

### ISSUE THREAD

**Issue by panruiqing** [stschiff/msmc-tools#26]
Dear Teacher:
I am a newer of msmc2 and I have some questions to ask for your help. I watch the manual of msmc and there are three steps to generate the input file of msmc. 
1. I want to know if l have  unrelated but not trios samples, need i pahses the Vcfs using shapeit. 
2. When i use shapeit ,maybe I need a genetic map, must i generate a genetic map using my samples F1 or orther lines?
3. I have unlreated samples. After i run run_shapeit.sh, When I using generate_multihetsep.py ,need i using "-trio"?
Thank you for you help , I am loking forward to get you generally reply.

**Comment by stschiff** [comment]
Sorry, I can't support phasing questions here. Please seek advice with the community around Shapeit2 or other phasing tools.
