### ISSUE TITLE
error in makeMappabilityMask.py

### ISSUE THREAD

**Issue by rillaxy** [stschiff/msmc-tools#29]
Hi Stephan,

1. I am currently using MSMC2 to inferred the population demographic history of wild rice(400Mb). I want to know it's necessary to generate an  additional mask per chromosome if i want to generate the input file for msmc. 

2.And whther the mappability mask is generanted by reference genome . 

3.When I generate the mappability mask for Reference genome accroding to  Heng Li's SNPable program ,I only get the chr1? why ?is the Heng Li's SNPable program  only  generate the singel chromosome ?so i must split my reference genome to 12 chromosome ?

`splitfa IRGSP-1.0_genome.fasta 35 | split -l 20000000`
`bwa index -a bwtsw IRGSP-1.0_genome.fasta`
`bwa aln -R 1000000 -O 3 -E 3 IRGSP-1.0_genome.fasta x* > xxaa.sai`
`bwa samse IRGSP-1.0_genome.fasta xxaa.sai x* > xxbb.sam.gz`
`gzip -dc xxbb.sam.gz | gen_raw_mask.pl > rawMask_35.fa`
`gen_mask` -l 35 -r 0.5 rawMask_35.fa > `mask_35_50.fa`
   it's my commond , andIRGSP-1.0_genome.fasta is my reference genome

Thanks in advance for your help!

rilla

**Comment by stschiff** [comment]
Sorry, I can’t support that step. Please look at Mallick et al. 2016 Nature (Supplement). They describe how they construct masks.

Stephan

**Comment by rillaxy** [comment]
Thanks for your reply.I will do my best to finish inferring the population demographic history of wild rice.


Rilla
------------------ 原始邮件 ------------------
发件人: "Stephan Schiffels"<notifications@github.com>;
发送时间: 2019年9月11日(星期三) 晚上11:28
收件人: "stschiff/msmc-tools"<msmc-tools@noreply.github.com>;
抄送: "冰清玉洁"<453005009@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [stschiff/msmc-tools] error in makeMappabilityMask.py (#29)



Sorry, I can’t support that step. Please look at Mallick et al. 2016 Nature (Supplement). They describe how they construct masks.
 
 Stephan

**Comment by rillaxy** [comment]
Hi,Stephan.I have solved the problem of mask. But when I have run into the issue with the decode.
when I run the command "make build/decode" or "make decode" in msmc2, it can't generate the decode.Below is my error message.


dmd -O /home/xy/program/gsl2.5/lib/libgsl.a /home/xy/program/gsl2.5/lib/libgslcblas.a -odbuild -ofbuild/decode model/transition_rate.d model/stateVecAllocator.d model/gsl_matrix_vector.d model/psmc_hmm.d model/propagation_core.d model/time_intervals.d model/psmc_model.d model/stateVec.d model/data.d decode.d
unable to fork: Cannot allocate memory
Makefile:28: recipe for target 'build/decode' failed
make: *** [build/decode] Error 255



I am looking forward to hearing from you .Thank you very much.
Rilla
------------------ 原始邮件 ------------------
发件人: "Stephan Schiffels"<notifications@github.com>;
发送时间: 2019年9月11日(星期三) 晚上11:28
收件人: "stschiff/msmc-tools"<msmc-tools@noreply.github.com>;
抄送: "冰清玉洁"<453005009@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [stschiff/msmc-tools] error in makeMappabilityMask.py (#29)



Sorry, I can’t support that step. Please look at Mallick et al. 2016 Nature (Supplement). They describe how they construct masks.
 
 Stephan

**Comment by stschiff** [comment]
If this problem persists, please open a new issue in the MSMC repository, as this is a compilation issue.
