### ISSUE TITLE
Phasing Format

### ISSUE THREAD

**Issue by GabrieleNocchi** [stschiff/msmc-tools#30]
Hello,

First of all, thanks for the great software and detailed instructios.
I have a question, I am not sure if this is the right place to post it therefore I apologize if it is not.

Everything is very clear however I am working with a non-model organism and I am running msmc with 4 individuals (8 haplotypes). For each individual I have a phased vcf file generated with GATK haplotypecaller.

In my VCFs the FORMAT filed is:  GT:AD:DP:GQ:PGT:PID:PL

With PGT being the phasing, done by GATK.
Upon running generate_multihetsep.py however the resulting files do not seem to take in consideration my VCF phasing.

I am wondering whether I should reformat my phasing information differently as maybe genereate_multihetsep does not see the GATK PGT tag?

I have never used shapeit2 as I am working with non-model organisms therefore I can not run another phasing with that.

Many Thanks,

Gabriele

**Comment by GabrieleNocchi** [comment]
I think I have sorted it. I believe that generate_multihetsep.py wants the phasing on the GT tag.

So if anyone has my issue, with the phasing in the GATK PGT tag, you can very easily put it on the GT tag with:

awk 'BEGIN{FS=OFS="\t"} {for (i=10;i<=NF;i++) { split($i,f,/:/); if (f[5]~/\|/) sub(/^[^:]+/,f[5],$i) } }1' input.gatk.vcf > output.mscmready.vcf

Taken from: https://gatkforums.broadinstitute.org/gatk/discussion/8526/using-combinevariants-to-update-gt-fields-with-phasing-information


Cheers

**Comment by stschiff** [comment]
OK, thanks, didn't know that there were different ways to convey phasing information. Yes, I assume it's encoded in the GT, like `0|1` or so.
