### ISSUE TITLE
Error in tutorial: Estimating population separation history 

### ISSUE THREAD

**Issue by alta7499** [stschiff/msmc-tools#32]
Dear Stephan and members of the community,

Thankyou for developing this program. I am learning the ropes of the program through the tutorial. When i reached the part to estimate population separation history, i encountered an error. it goes by this (screenshot is also attached) :

`./msmc2_linux64bit -t 4 I 0-4,0-5,1-4,1-5 -s -p 1*2+15*1+1*2 -o AFR_EUR.msmc2 EUR_AFR.chr1.multihetsep.txt`

error in parsing command line: std.exception.ErrnoException@std/stdio.d(393): Cannot open file `I' in mode `r' (No such file or directory)
----------------
??:? @safe shared(core.stdc.stdio._IO_FILE)* std.exception.__T12errnoEnforceTPOS4core4stdc5stdio8_IO_FILEVAyaa11_7374642f737464696f2e64Vmi393Z.errnoEnforce(shared(core.stdc.stdio._IO_FILE)*, lazy immutable(char)[]) [0x602e45]
??:? ref @safe std.stdio.File std.stdio.File.__ctor(immutable(char)[], const(char[])) [0x5dabf6]
??:? ulong model.data.getNrHaplotypesFromFile(immutable(char)[]) [0x51f4b7]
??:? void msmc2.parseCommandLine(immutable(char)[][]) [0x572d41]
??:? _Dmain [0x5728d3]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5cbc56]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5cbbac]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5cbc12]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5cbbac]
??:? _d_run_main [0x5cbb09]
??:? main [0x57bbc5]
??:? __libc_start_main [0xa0254f44]

![image](https://user-images.githubusercontent.com/67361763/85780872-ab2b4980-b757-11ea-8313-d8ed245d9cbe.png)

I made sure that all the necessary input is there and followed the command line as stated in the guide. I had run previous steps successfully. for this part, i tried both multihetsep.txt file i generated and the one that comes from the tutorial, but it still doesn't work. For the msmc2 binary, i used the latest version (v2.1.2, though it says 2.1.1. when i run the msmc2) downloaded from the "release" tab in github. Is there a solution to this problem? perhaps there is a package or library i need to install prior to running this? Thanks in advance, your help is much appreciated!

Best Regards,
alta7499

**Comment by stschiff** [comment]
You have typed `I` in the command line, but I think you need `-I`.

**Comment by alta7499** [comment]
Hi Stephan,

Thanks for the prompt reply. i have tried as you recommended, it works well. i have tried that in the past, but it resulted in error as well. i think i was using older version of the binary that time. Anyway, Thanks a lot for the clarification and sorry for the inconvenience. i wish you well!
