### ISSUE TITLE
Error when running ./generate_multihetsep.py

### ISSUE THREAD

**Issue by barlavi1** [stschiff/msmc-tools#33]
Hello,
I am trying to generate the multihetsep file for one sample using the generate_multihetsep.py.
I inserted 
(1) a bed file which was generated using the bamCaller.py,
(2) a bed file for my reference (genome.fa), which is an empty file, since I want to use the entire genome. 
(3) a vcf.gz 

 ./generate_multihetsep.py --mask sample.bed \  --mask genome.mask.fa \  sample.vcf.gz

The error I get:
**generate_multihetsep.py: error: unrecognized arguments:  sample.vcf.gz**

I appreciate your help,
Bar

**Comment by stschiff** [comment]
Have you tried without the back-slashes?
