### ISSUE TITLE
Tutorial input file link is broken

### ISSUE THREAD

**Issue by ejquinlan** [stschiff/msmc-tools#34]
The input data link in msmc-tutorial/guide.md isn't working.

https://oc.gnz.mpg.de/owncloud/index.php/s/786PRKqWBYXm0YT times out when trying to connect (ERR_CONNECTION_TIMED_OUT)

Perhaps the files could be rehosted? The [link in the primary README](https://shh-cloud.gnz.mpg.de/index.php/s/2Z6wxNbEwxM6ERK) is working fine for me.

**Comment by stschiff** [comment]
Thanks, I'll see to it next week.

**Comment by stschiff** [comment]
I've just updated it. The correct link is https://shh-cloud.gnz.mpg.de/index.php/s/TA97LimSB7TFPgi
