### ISSUE TITLE
Alterations for bcftools mpileup

### ISSUE THREAD

**Issue by Matthew-Holding** [stschiff/msmc-tools#35]
Hello,

I'm wondering if you have a variant on the scripts to build the consensus that will take input from bcftools mpileup instead of samtools mpileup? Trying to simply replace samtools mpileup with bcftools mpileup seems to break the downstream scripts.

My goal is to take a minimap2 alignment of PacBio ccs reads to a reference, use bcftools mpileup to process the alignment.bam, and then get to a suitable input for msmc. 

Thank you!

**Comment by stschiff** [comment]
I have currently no plans to implement new features here. Sorry.
