### ISSUE TITLE
Tutorial data link is dead

### ISSUE THREAD

**Issue by masaomi** [stschiff/msmc-tools#36]
Dear Stephan,

The data used in the tutorial

https://oc.gnz.mpg.de/owncloud/index.php/s/786PRKqWBYXm0YT

is not available. I am not sure if it does not work temporarily, though. 

Thanks!!
Masa

**Comment by stschiff** [comment]
Yes, sorry, I've just updated it. The correct one is https://shh-cloud.gnz.mpg.de/index.php/s/TA97LimSB7TFPgi

**Comment by masaomi** [comment]
Thank you so much for the quick response!!
Masa
