### ISSUE TITLE
error in bamCaller.py

### ISSUE THREAD

**Issue by YueqiTao** [stschiff/msmc-tools#41]
Hi!

There is an error in my log file when run bamCaller.py. 

Traceback (most recent call last):
  File "/ebio/abt6/ytao/software/msmc-tools/bamCaller.py", line 36, in <module>
    assert fields[0] == chr_, "found multiple chromosomes"
AssertionError: found multiple chromosomes

Could you please help me to solve it? Many thanks!

Best regards,
Yueqi

**Comment by stschiff** [comment]
This script is very old and I don't actively maintain it anymore (it's python, so I expect people to just take it as a script and adapt to their needs). But for what it's worth: In MSMC I generally assume you're processing a single chromosome at a time. Please check the script and your input to debug. Thanks.
