### ISSUE TITLE
Phase data using BEAGLE

### ISSUE THREAD

**Issue by jiangzy26** [stschiff/msmc-tools#43]
Hi,
    I am trying msmc, the vcf file should be phased, the shapeit software need Map files and REF_PANEL, but my research species has no such files, I would like to use BEAGLE, could you share the steps to get the results as shapeit?
    Thank you very much!

**Comment by stschiff** [comment]
I'm afraid I can't support bioinformatic processing issues for MSMC, they are far too diverse and depend on many things I don't even know for you data. If you want to use Beagle, I think that's possible, but please consult the Beagle documentation or the community for how to run it and use it.
