### ISSUE TITLE
generate_multihetsep.py

### ISSUE THREAD

**Issue by yangwukaidi** [stschiff/msmc-tools#52]
hi，I had a problem recently
The commands I use are as follows:
python2.7 generate_multihetsep.py --chr 1 --mask 1Z-CWX10A-1.mask.bed.gz --mask reLG01.mask.bed.gz  1Z-CWX10A.vcf > LG01.multihetsep.txt
But I got an error:
File "/home/user/download/gsl-2.6/msmc2-master/build/release/generate_multihetsep.py", line 75
    print ("Non-diploid SNP found and considered as unphased data: %s" % geno, file=sys.stderr)
The mask. file of the sample I obtained using the bam. file.
The vcf. file for the sample was also obtained using the bam. file, and then phasing the vcf. file using BEAGLE.
How can I solve this error?
Looking forward to your reply!

**Comment by stschiff** [comment]
What you printed here is not an error. What is the error?
The line you quote above from `generate_multihetsep.py` simply triggers an output that a SNP with more than 2 alleles is considered unphased. That's not an error, and the line 75 in the file doesn't trigger an error.

**Comment by yangwukaidi** [comment]
Thank you for your reply!
I'm sorry that I missed the last sentence it outputs after executing the command: "syntaxerror: invalid syntax."
So, 
python2.7 generate_multihetsep.py --chr 1 --mask 1Z-CWX10A-1.mask.bed.gz --mask reLG01.mask.bed.gz 1Z-CWX10A.vcf > LG01.multihetsep.txt.
After command execution, the full output is as follows
    File "/home/user/download/gsl-2.6/msmc2-master/build/release/generate_multihetsep.py", line 75
       print ("Non-diploid SNP found and considered as unphased data: %s" % geno, file=sys.stderr)
                                                                                                                                           ^
syntaxerror: invalid syntax
In addition, this "^" is also in the output, I hope you did not ignore.

In fact, I tried too many samples. 
Same as the former, the mask. file of samples I obtained using the bam. file, the vcf. file for samples was also obtained using the bam. file, and then phasing the vcf. file using BEAGLE.
The commands I use are as follows:
 python2.7 /home/user/download/gsl-2.6/msmc2-master/build/release/generate_multihetsep.py --chr 1 --mask 1Z-CWX10A-1.mask.bed.gz --mask 1Z-DHS8A-1.mask.bed.gz --mask 2QBZ-LFT3.mask.bed.gz --mask 2QBZ-LFT11-1.mask.bed.gz --mask 3HNHZ-BLM3-1.mask.bed.gz --mask 3HNHZ-DQ-1.mask.bed.gz --mask 4YZ-BLM2-1.mask.bed.gz --mask 4YZ-BLM2-1.mask.bed.gz --mask reLG01.mask.bed.gz 1Z-CWX10A-1.vcf 1Z-DHS8A-1.vcf 2QBZ-LFT3-1.vcf 2QBZ-LFT11-1.vcf 3HNHZ-BLM3-1.vcf 3HNHZ-DQ-1.vcf 4YZ-BLM2-1.vcf 4YZ-BLM3-1.vcf > LG01.multihetsep.txt
But I still get the same output, as follows:
  File "/home/user/download/gsl-2.6/msmc2-master/build/release/generate_multihetsep.py", line 75
    print ("Non-diploid SNP found and considered as unphased data: %s" % geno, file=sys.stderr)
                                                                                                                                        ^
SyntaxError: invalid syntax

Looking forward to your reply!

**Comment by stschiff** [comment]
It's a python3-script, as also indicated in the shebang at the top. It doesn't work with python2.7

**Comment by yangwukaidi** [comment]
Thank you for your reply!
Following your advice, I ran the program again, using python version 3.9.12
But it still prints a problem and doesn't run properly, even though it doesn't mention error.
My command and all the output it returns are as follows:

(bio39) [user@localhost phaseVCF]$ python /home/user/download/gsl-2.6/msmc2-master/build/release/generate_multihetsep.py --chr 1 --mask 1Z-CWX10A-1.mask.bed.gz --mask 1Z-DHS8A-1.mask.bed.gz --mask 2QBZ-LFT3.mask.bed.gz --mask 2QBZ-LFT11-1.mask.bed.gz --mask 3HNHZ-BLM3-1.mask.bed.gz --mask 3HNHZ-DQ-1.mask.bed.gz --mask 4YZ-BLM2-1.mask.bed.gz --mask 4YZ-BLM2-1.mask.bed.gz --mask reLG01.mask.bed.gz 1Z-CWX10A-1.vcf 1Z-DHS8A-1.vcf 2QBZ-LFT3-1.vcf 2QBZ-LFT11-1.vcf 3HNHZ-BLM3-1.vcf 3HNHZ-DQ-1.vcf 4YZ-BLM2-1.vcf 4YZ-BLM3-1.vcf > LG01.multihetsep.txt
generating msmc input file with 16 haplotypes
Traceback (most recent call last):
  File "/home/user/download/gsl-2.6/msmc2-master/build/release/generate_multihetsep.py", line 195, in <module>
    joinedVcfIterator = JoinedVcfIterator(args.files, trios)
  File "/home/user/download/gsl-2.6/msmc2-master/build/release/generate_multihetsep.py", line 131, in __init__
    self.current_lines = [next(v) for v in self.vcfIterators]
  File "/home/user/download/gsl-2.6/msmc2-master/build/release/generate_multihetsep.py", line 131, in <listcomp>
    self.current_lines = [next(v) for v in self.vcfIterators]
  File "/home/user/download/gsl-2.6/msmc2-master/build/release/generate_multihetsep.py", line 61, in __next__
    line = next(self.file)
  File "/home/user/anaconda3/envs/bio39/lib/python3.9/gzip.py", line 313, in read1
    return self._buffer.read1(size)
  File "/home/user/anaconda3/envs/bio39/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/user/anaconda3/envs/bio39/lib/python3.9/gzip.py", line 487, in read
    if not self._read_gzip_header():
  File "/home/user/anaconda3/envs/bio39/lib/python3.9/gzip.py", line 435, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'##')

How do I get the program to work?
Looking forward to your reply!

**Comment by yangwukaidi** [comment]
@stschiff 
Looking forward to your reply！

**Comment by yangwukaidi** [comment]
Hi, dear stschiff.
Thank you very much for your reply, but there is a new situation of my problem. 
I am using python 3.9. The command line I use and output are as follows.
python generate_multihetsep.py --chr 1 --mask 1Z-CWX10A-1.mask.bed.gz --mask 2QBZ-LFT3-1.mask.bed.gz --mask 3HNHZ-BLM3-1.mask.bed.gz --mask 4YZ-BLM2-1.mask.bed.gz --mask reLG01.mask.bed.gz 1Z-CWX10A-1.vcf.gz 2QBZ-LFT3-1.vcf.gz 3HNHZ-BLM3-1.vcf.gz 4YZ-BLM2-1.vcf.gz > LG01.multihetsep.txt
generating msmc input file with 8 haplotypes
Traceback (most recent call last):
  File "generate_multihetsep.py", line 195, in <module>
     joinedVcfIterator = JoinedVcfIterator(args.files, trios)
  File "generate_multihetsep.py", line 131, in __init__
    self.current_lines = [next(v) for v in self.vcfIterators]
  File "generate_multihetsep.py", line 131, in <listcomp>
    self.current_lines = [next(v) for v in self.vcfIterators]
  File "generate_multihetsep.py", line 73, in __next__
    geno = fields[9][:3]
IndexError: list index out of range

I saw that others had a similar problem, the difference being that the last line of the output returned by the others had "chromosome = fields[0]", whereas I was " geno = fields[9][:3]" 
 What is the cause of this error, and how can I fix it?

Looking forward to your reply!

**Comment by yangwukaidi** [comment]
@stschiff Hi, dear stschiff.
Thank you very much for your reply, but there is a new situation of my problem.
I am using python 3.9. The command line I use and output are as follows.
python generate_multihetsep.py --chr 1 --mask 1Z-CWX10A-1.mask.bed.gz --mask 2QBZ-LFT3-1.mask.bed.gz --mask 3HNHZ-BLM3-1.mask.bed.gz --mask 4YZ-BLM2-1.mask.bed.gz --mask reLG01.mask.bed.gz 1Z-CWX10A-1.vcf.gz 2QBZ-LFT3-1.vcf.gz 3HNHZ-BLM3-1.vcf.gz 4YZ-BLM2-1.vcf.gz > LG01.multihetsep.txt
generating msmc input file with 8 haplotypes
Traceback (most recent call last):
File "generate_multihetsep.py", line 195, in
joinedVcfIterator = JoinedVcfIterator(args.files, trios)
File "generate_multihetsep.py", line 131, in init
self.current_lines = [next(v) for v in self.vcfIterators]
File "generate_multihetsep.py", line 131, in
self.current_lines = [next(v) for v in self.vcfIterators]
File "generate_multihetsep.py", line 73, in next
geno = fields[9][:3]
IndexError: list index out of range
@stschiff Hi, dear stschiff.
Thank you very much for your reply, but there is a new situation of my problem.
I am using python 3.9. The command line I use and output are as follows.
python generate_multihetsep.py --chr 1 --mask 1Z-CWX10A-1.mask.bed.gz --mask 2QBZ-LFT3-1.mask.bed.gz --mask 3HNHZ-BLM3-1.mask.bed.gz --mask 4YZ-BLM2-1.mask.bed.gz --mask reLG01.mask.bed.gz 1Z-CWX10A-1.vcf.gz 2QBZ-LFT3-1.vcf.gz 3HNHZ-BLM3-1.vcf.gz 4YZ-BLM2-1.vcf.gz > LG01.multihetsep.txt
generating msmc input file with 8 haplotypes
Traceback (most recent call last):
File "generate_multihetsep.py", line 195, in
joinedVcfIterator = JoinedVcfIterator(args.files, trios)
File "generate_multihetsep.py", line 131, in init
self.current_lines = [next(v) for v in self.vcfIterators]
File "generate_multihetsep.py", line 131, in
self.current_lines = [next(v) for v in self.vcfIterators]
File "generate_multihetsep.py", line 73, in next
geno = fields[9][:3]
IndexError: list index out of range

I saw that others had a similar problem, the difference being that the the last line of output returned by other people's command is "chromosome = fields[0]", whereas mine is " geno = fields[9][:3]"
What is the cause of this error, and how can I fix it?

Looking forward to your reply!

I saw that others had a similar problem, the difference being that the the last line of output returned by other people's command is "chromosome = fields[0]", whereas mine is " geno = fields[9][:3]"
What is the cause of this error, and how can I fix it?

Looking forward to your reply!

**Comment by yangwukaidi** [comment]
@stschiff Hi, dear stschiff.
Thank you very much for your reply, but there is a new situation of my problem.
I am using python 3.9. The command line I use and output are as follows.
python generate_multihetsep.py --chr 1 --mask 1Z-CWX10A-1.mask.bed.gz --mask 2QBZ-LFT3-1.mask.bed.gz --mask 3HNHZ-BLM3-1.mask.bed.gz --mask 4YZ-BLM2-1.mask.bed.gz --mask reLG01.mask.bed.gz 1Z-CWX10A-1.vcf.gz 2QBZ-LFT3-1.vcf.gz 3HNHZ-BLM3-1.vcf.gz 4YZ-BLM2-1.vcf.gz > LG01.multihetsep.txt
generating msmc input file with 8 haplotypes
Traceback (most recent call last):
File "generate_multihetsep.py", line 195, in
joinedVcfIterator = JoinedVcfIterator(args.files, trios)
File "generate_multihetsep.py", line 131, in init
self.current_lines = [next(v) for v in self.vcfIterators]
File "generate_multihetsep.py", line 131, in
self.current_lines = [next(v) for v in self.vcfIterators]
File "generate_multihetsep.py", line 73, in next
geno = fields[9][:3]
IndexError: list index out of range

I saw that others had a similar problem, the difference being that the the last line of output returned by other people's command is "chromosome = fields[0]", whereas mine is " geno = fields[9][:3]"
What is the cause of this error, and how can I fix it?

Looking forward to your reply!

I saw that others had a similar problem, the difference being that the the last line of output returned by other people's command is "chromosome = fields[0]", whereas mine is " geno = fields[9][:3]"
What is the cause of this error, and how can I fix it?

Looking forward to your reply!

**Comment by yangwukaidi** [comment]
@stschiff Hi, dear stschiff.
Thank you very much for your reply, but there is a new situation of my problem.
I am using python 3.9. The command line I use and output are as follows.
python generate_multihetsep.py --chr 1 --mask 1Z-CWX10A-1.mask.bed.gz --mask 2QBZ-LFT3-1.mask.bed.gz --mask 3HNHZ-BLM3-1.mask.bed.gz --mask 4YZ-BLM2-1.mask.bed.gz --mask reLG01.mask.bed.gz 1Z-CWX10A-1.vcf.gz 2QBZ-LFT3-1.vcf.gz 3HNHZ-BLM3-1.vcf.gz 4YZ-BLM2-1.vcf.gz > LG01.multihetsep.txt
generating msmc input file with 8 haplotypes
Traceback (most recent call last):
File "generate_multihetsep.py", line 195, in
joinedVcfIterator = JoinedVcfIterator(args.files, trios)
File "generate_multihetsep.py", line 131, in init
self.current_lines = [next(v) for v in self.vcfIterators]
File "generate_multihetsep.py", line 131, in
self.current_lines = [next(v) for v in self.vcfIterators]
File "generate_multihetsep.py", line 73, in next
geno = fields[9][:3]
IndexError: list index out of range

I saw that others had a similar problem, the difference being that the the last line of output returned by other people's command is "chromosome = fields[0]", whereas mine is " geno = fields[9][:3]"
What is the cause of this error, and how can I fix it?

Looking forward to your reply!

**Comment by stschiff** [comment]
see my comment to your other post. This is hard to support, as I don't know your input files. Generally, I admit that these python preparation scripts aren't coded in a completely "fire-and-forget" way, but require some work in looking at python code and bioinformatics formats, such as VCF.

**Comment by yangwukaidi** [comment]
Thank you very much for your reply!
According to your suggestion, I checked the VCF file, there were some problems, I re-ran the script after solving them, but it returned an error, as follows:
python generate_multihetsep.py --chr LG01 --mask 1Z-CWX10A-1.mask.bed.gz --mask 2QBZ-LFT3-1.mask.bed.gz --mask 3HNHZ-BLM3-1.mask.bed.gz --mask 4YZ-BLM2-1.mask.bed.gz --mask re_chrLG01.mask.bed.gz 1Z-CWX10A-1.vcf.gz 2QBZ-LFT3-1.vcf.gz 3HNHZ-BLM3-1.vcf.gz 4YZ-BLM2-1.vcf.gz > LG01.multihetsep.txt
generating msmc input file with 8 haplotypes
adding mask: 1Z-CWX10A-1.mask.bed.gz
adding mask: 2QBZ-LFT3-1.mask.bed.gz
adding mask: 3HNHZ-BLM3-1.mask.bed.gz
adding mask: 4YZ-BLM2-1.mask.bed.gz
adding mask: re_chrLG01.mask.bed.gz
Traceback (most recent call last):
  File "generate_multihetsep.py", line 200, in <module>
    maskIterators.append(MaskIterator(f))
  File "generate_multihetsep.py", line 19, in __init__
    self.readLine()
  File "generate_multihetsep.py", line 23, in readLine
    line = next(self.file)
  File "/home/user/anaconda3/envs/bio39/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
How can I solve this problem? 
Looking forward to your reply!

**Comment by yangwukaidi** [comment]
Thanks for your reply. 
According to your suggestion, I have solved my problem and it can run normally. In addition, thank you very much for your suggestion that I should improve my ability in bioinformatics and python application.
 I'm sorry to admit that I'm really a novice at this. 
However, I will keep improving.
Thanks again for your help! Wish you a happy life!
