### ISSUE TITLE
Question regarding interpret the result of combineCrossCoal

### ISSUE THREAD

**Issue by willright28** [stschiff/msmc-tools#57]
Hi @stschiff and all users,

I hope you all doing well.

I have a small question regarding the interpretion of result of combineCrossCoal. I have two pops with an average weighted Fst 0.15, and I want to study the separation time for them. Please see the result attached below, how to explain the valley-shaped curve? It started the separation between 20~30 kyr and reach the mid-point then rebound due to a potential gene flow?
![image](https://github.com/user-attachments/assets/df4d3d99-964c-48c8-bdd5-47ee43ed7b8e)

Many thanks for your time and attention!

Best,
willright28

**Comment by stschiff** [comment]
Hard to say. In the most recent time segments, there are sometimes weird things going on due to noise. I would not trust this. Arguably the drop around 25,000 years ago is more what you're looking for in terms of time estimate. You can also check the population size curves of the two populations and see where they diverge.

**Comment by willright28** [comment]
Hi @stschiff ,

Thanks for your reply!

The noise may be due to the unphased data. I've corrected that, and the updated result is shown below. It seems the relative cross-coalescence rate exceeds value 1.0 in ancient times, how can this be explained? The second figure is the population size curves of the two populations. Based on the two results combined, although a time at mid-point of 0.5 is often taken to be the seperation time, could I draw a preliminary conclusion that the seperation time is ~ 1 million years ago?

![image](https://github.com/user-attachments/assets/98b04c0e-fd80-4e9a-ae32-2843becd91b6)
![image](https://github.com/user-attachments/assets/8f2136bc-e932-4769-acaa-4dd364b7a0a4)

Many thanks for your time and attention!

Best,
willright28

**Comment by stschiff** [comment]
Well, for what it's worth, this looks actually very clean now. That the CCR exceeds 1 is just an artefact of the simplistic way how it's computed. There is no model or anything that constrains it to between 0 and 1. If you were to plot the inverse cross-coalescence rate into the Pop-size-plot, you would find that they all are very similar >1Mya and then the inverse CCR starts growing above the two individual pop-size curves. That's exactly the hallmark of a separation. I wouldn't necessarily say that the "separation time" is >1Mya, that is more fuzzy I believe. What we usually do is take the time at which the _relative_ CCR crosses the 0.5 level, so in your case that would be perhaps a few hundred thousand years or so. But ultimately of course a point estimate for a separation process is simplistic. The reality may be more that it was a slow separation of increasing population structure, up to the point where gene flow between the two groups stopped?

You may want to look at [MSMC-IM](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008552) to model this more explicitly

**Comment by willright28** [comment]
Thanks for your guidance, it is very helpful!
