### ISSUE TITLE
plot_utils.py difficulty

### ISSUE THREAD

**Issue by MickWest1** [stschiff/msmc-tools#6]
Hi, whenever I try to run the plot_utils.py script i come up with the error
Traceback (most recent call last):
  File "./plot_utils.py", line 4, in <module>
    from scipy.interpolate import interp1d 
ImportError: No module named 'scipy'

The problem is I have already installed scipy but this error stillcomes up.
Any help would be greatly appreciated. Thanks

**Comment by ajsams** [comment]
Are you using python3 and have scipy installed specifically for python3?  That's the first potential problem that came to mind.

**Comment by stschiff** [comment]
Yes, you need spicy installed for python3. python2 and python3 operate on different stacks of installed libraries.
You can of course also just try to recode the script for python2, shouldn’t be too hard.

Stephan

**Comment by MickWest1** [comment]
Ok, thanks. When I run ./plot_utils.py the error no longer comes up but neither does a command. Would you be able to tell me the command for it so I can test it properly? I have tried using my ./plot_utils.py msmc output files but nothing seems to be happening...

**Comment by stschiff** [comment]
Sorry, but it’s not meant to be a simple script. plot_utils.py is meant to be used as a library to import for your own plotting scripts. I mainly included it to give people idea how to plot certain things, like tMRCA distributions.

Stephan

**Comment by MickWest1** [comment]
Ok thanks. I actually don't have a plotting script of my own, any advice on how to put one together or an example one I could look at and work backwards from?
