### ISSUE TITLE
Error on generate_multihetsep.py 

### ISSUE THREAD

**Issue by MaoYafei** [stschiff/msmc-tools#7]
Dear all,

I am working on non-human organism. I followed your guide and generated masked file and try to run generate_multihetsep.py.

> /apps/free/python/3.5.0/bin/python3 /work/student/yafei-mao/msmc/msmc-tools/generate_multihetsep.py --mask=Mi2_sc1_mask.bed.gz --mask=Mi4_sc1_mask.bed.gz --mask=Adif_chrsc0000001.mask.bed.gz Mi2_sc1.vcf.gz Mi4_sc1.vcf.gz 

Got error looks like below:

> generating msmc input file with 4 haplotypes
> adding mask: Mi2_sc1_mask.bed.gz
> adding mask: Mi4_sc1_mask.bed.gz
> adding mask: Adif_chrsc0000001.mask.bed.gz
> Traceback (most recent call last):
>   File "/work/student/yafei-mao/msmc/msmc-tools/generate_multihetsep.py", line 212, in <module>
>     if mergedMask.getVal(pos):
>   File "/work/student/yafei-mao/msmc/msmc-tools/generate_multihetsep.py", line 49, in getVal
>     return all((m.getVal(pos) for m in self.maskIterators))
>   File "/work/student/yafei-mao/msmc/msmc-tools/generate_multihetsep.py", line 49, in <genexpr>
>     return all((m.getVal(pos) for m in self.maskIterators))
>   File "/work/student/yafei-mao/msmc/msmc-tools/generate_multihetsep.py", line 37, in getVal
>     while pos > self.end and not self.eof:
> AttributeError: 'MaskIterator' object has no attribute 'end'

Could you help me figure it out?
Thanks a lot,

Best, 
Yafei

**Comment by stschiff** [comment]
Is it possible that one of your mask files is empty or ends prematurely?

**Comment by MaoYafei** [comment]
Hi Stephan,

Thanks for your reply~
As you said, one of files is empty, but now, I figure it out. And generate the input files and then run msmc.

> /work/student/yafei-mao/msmc/msmc-1.0.0/build/msmc --fixedRecombination -o test.output -t 24 test1.input test2.input

got error below:

> read 6505 SNPs from file test1.input
> read 5466 SNPs from file test2.input
> estimating scaled mutation rate: 0.000809016
> input files:         ["test1.input", "test2.input"]
> maxIterations:       20
> mutationRate:        0.000809016
> recombinationRate:   0.000202254
> subpopLabels:        [0, 0]
> timeSegmentPattern:  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
> nrThreads:           24
> nrTtotSegments:      40
> verbose:             false
> outFilePrefix:       test.output
> naiveImplementation: false
> hmmStrideWidth:      1000
> fixedPopSize:        false
> fixedRecombination:  true
> initialLambdaVec:    []
> directedEmissions:   false
> skipAmbiguous:       false
> indices:             [0, 1]
> logging information written to test.output.log
> loop information written to test.output.loop.txt
> final results written to test.output.final.txt
> [1/20] Baumwelch iteration
> - [1/2] Expectation StepSegmentation fault (core dumped)

Could you help me again?
Thanks a lot~

Best, 
Yafei

**Comment by stschiff** [comment]
Hi Yafei,
these are WAY too few SNPs. You are analysing only ~10,000 SNPs, and are trying to fit 25 parameters. There is probably massive overfitting going on, which can sometimes throw exceptions. You need much more data for MSMC. It is also possible that your machine ran out of memory.

Stephan

**Comment by MaoYafei** [comment]
Hi Stephan,

Thanks for your quick and useful reply. 

Actually, I used one scaffold data of two inds to test pipeline there. But I have 3 subpopulation and I have 30 inds for each of them. According to information in google groups, it suggested that it is enough for analysizing one population using 8 inds, is it right?

I described my pipeline below:
1. generate bed/vcf files of each scaffolds (>100kb) for random 7 inds per population.
2. generate inputfile with 8 inds data using  generate_multihetsep.py for each scaffolds. And thus, I would have the inputfiles for each scaffolds.
3. I use msmc to do analysis below:

> /work/student/yafei-mao/msmc/msmc-1.0.0/build/msmc -o Mi_output Mi_sc0000001.input Mi_sc0000008.input Mi_sc0000009.input Mi_sc0000014.input Mi_sc0000031.input Mi_sc0000018.input Mi_sc0000010.input Mi_sc0000005.input Mi_sc0000039.input Mi_sc0000020.input Mi_sc0000086.input Mi_sc0000012.input Mi_sc0000017.input Mi_sc0000022.input Mi_sc0000017.input Mi_sc0000042.input 

And I also got the error:

> read 8800 SNPs from file Mi_sc0000001.input
> read 7939 SNPs from file Mi_sc0000008.input
> read 4797 SNPs from file Mi_sc0000009.input
> read 4666 SNPs from file Mi_sc0000014.input
> read 4640 SNPs from file Mi_sc0000031.input
> read 4361 SNPs from file Mi_sc0000018.input
> read 3987 SNPs from file Mi_sc0000010.input
> read 3672 SNPs from file Mi_sc0000005.input
> read 3545 SNPs from file Mi_sc0000039.input
> read 3260 SNPs from file Mi_sc0000020.input
> read 3096 SNPs from file Mi_sc0000086.input
> read 3100 SNPs from file Mi_sc0000012.input
> read 2898 SNPs from file Mi_sc0000017.input
> read 2983 SNPs from file Mi_sc0000022.input
> read 2898 SNPs from file Mi_sc0000017.input
> read 2777 SNPs from file Mi_sc0000042.input
> estimating scaled mutation rate: 0.00189947
> input files:         ["Mi_sc0000001.input", "Mi_sc0000008.input", "Mi_sc0000009.input", "Mi_sc0000014.input", "Mi_sc0000031.input", "Mi_sc0000018.input", "Mi_sc0000010.input", "Mi_sc0000005.input", "Mi_sc0000039.input", "Mi_sc0000020.input", "Mi_sc0000086.input", "Mi_sc0000012.input", "Mi_sc0000017.input", "Mi_sc0000022.input", "Mi_sc0000017.input", "Mi_sc0000042.input"]
> maxIterations:       20
> mutationRate:        0.00189947
> recombinationRate:   0.000474869
> subpopLabels:        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
> timeSegmentPattern:  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
> nrThreads:           24
> nrTtotSegments:      40
> verbose:             false
> outFilePrefix:       Mi_output
> naiveImplementation: false
> hmmStrideWidth:      1000
> fixedPopSize:        false
> fixedRecombination:  false
> initialLambdaVec:    []
> directedEmissions:   false
> skipAmbiguous:       false
> indices:             [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
> logging information written to Mi_output.log
> loop information written to Mi_output.loop.txt
> final results written to Mi_output.final.txt
> [9/16] estimating total branchlengthsSegmentation fault (core dumped)

Plus: Mi_sc${i}.input was generated by below command:

> for i in $files
> do
> /apps/free/python/3.5.0/bin/python3 /work/student/yafei-mao/msmc/msmc-tools/generate_multihetsep.py --mask=Mi2/Mi2_sc${i}_mask.bed.gz \
> --mask=Mi3/Mi3_sc${i}_mask.bed.gz \
> --mask=Mi6/Mi6_sc${i}_mask.bed.gz \
> --mask=My3/My3_sc${i}_mask.bed.gz \
> --mask=My6/My6_sc${i}_mask.bed.gz \
> --mask=Ms3/Ms3_sc${i}_mask.bed.gz \
> --mask=Ms6/Ms6_sc${i}_mask.bed.gz \
> --mask /work/student/yafei-mao/msmc/msmc-tools/Mask/Adif_chr${i}.mask.bed.gz \
> Mi2/Mi2_sc${i}.vcf.gz \
> Mi3/Mi3_sc${i}.vcf.gz \
> Mi6/Mi6_sc${i}.vcf.gz \
> My3/My3_sc${i}.vcf.gz \
> My6/My6_sc${i}.vcf.gz \
> Ms3/Ms3_sc${i}.vcf.gz \
> Ms6/Ms6_sc${i}.vcf.gz > All/Mi_${i}.input 
> done

Plus again: Mi{k}/My{k}/Ms{k} are inds which belongs some subpopulation.

Is this pipeline totally wrong for msmc? Or It means that there are no enough data for msmc analysis in my case?
Thanks a lot~

Best, 
Yafei

**Comment by stschiff** [comment]
Please try again with msmc2. Thanks.
